# Generated by Django 3.0.1 on 2020-01-09 16:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cables',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('cable_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип кабеля')),
                ('cable_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя кабеля')),
                ('pare_qty', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Количество пар')),
                ('wire_qty', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Количество жил')),
                ('cable_section', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Сечение кабеля')),
            ],
            options={
                'verbose_name': 'Тип кабеля',
                'verbose_name_plural': 'Типы кабелей',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='category',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='comp_type',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип компании',
                'verbose_name_plural': 'Типы компаний',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='company',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование компании')),
                ('name_eng', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Наименование английское')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('local', models.BooleanField(blank=True, db_index=True, default=False, null=True, verbose_name='Локальное или нет')),
                ('rating', models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Рейтинг')),
            ],
            options={
                'verbose_name': 'Компания',
                'verbose_name_plural': 'Компании',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='contact',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('first_name', models.CharField(max_length=100, unique=True, verbose_name='Имя')),
                ('family_name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Фамилия')),
                ('third_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Отчество')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('position', models.CharField(blank=True, max_length=100, null=True, verbose_name='Должность')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, verbose_name='email')),
                ('site', models.URLField(blank=True, null=True, verbose_name='Сайт')),
                ('phone_mobile', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон мобильный')),
                ('phone_company', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон рабочий')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ['-family_name'],
            },
        ),
        migrations.CreateModel(
            name='control_interface',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование управляющего интерфейса')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('interface_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип управляющего интерфейса')),
                ('physic_range', models.CharField(blank=True, max_length=100, null=True, verbose_name='Диапазон')),
                ('cable_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.cables', verbose_name='Тип кабеля')),
            ],
            options={
                'verbose_name': 'Управляющий интерфейс',
                'verbose_name_plural': 'Управляющие интерфейсы',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='country',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='family',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Семейство',
                'verbose_name_plural': 'Семейства',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='good',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Название')),
                ('part_no', models.CharField(blank=True, db_index=True, max_length=100, null=True, unique=True, verbose_name='Заводской номер')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('purchase_price_wo_vat', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Закупочная цена, без НДС')),
                ('purchase_price_w_vat', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Закупочная цена, с НДС')),
                ('rrp_wo_vat', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Розница, без НДС')),
                ('rrp_price_w_vat', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Розница, с НДС')),
                ('discount_standart', models.FloatField(blank=True, null=True, verbose_name='Скидка стандартная')),
                ('discount_max', models.FloatField(blank=True, null=True, verbose_name='Скидка максимальная')),
                ('multiplayer_standart', models.FloatField(blank=True, null=True, verbose_name='Наценка стандартная')),
                ('multiplayer_min', models.FloatField(blank=True, null=True, verbose_name='Наценка минимальная')),
                ('profit_rrp', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Прибыль от розницы')),
                ('profit_standart', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Прибыль при стандартной скидке')),
                ('profit_min', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Прибыль при максимальной скидке')),
                ('delivery_time', models.TimeField(blank=True, null=True, verbose_name='Срок поставки')),
                ('doc_file', models.FileField(blank=True, null=True, upload_to='', verbose_name='Файл с документацией')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Изображение')),
                ('schematic', models.FileField(blank=True, null=True, upload_to='', verbose_name='Схема')),
                ('svg', models.FileField(blank=True, null=True, upload_to='', verbose_name='svg')),
                ('installation_time', models.FloatField(blank=True, null=True, verbose_name='Время на монтаж')),
                ('programming_time', models.FloatField(blank=True, null=True, verbose_name='Время на программирование')),
                ('comission_time', models.FloatField(blank=True, null=True, verbose_name='Время на пуско - наладку')),
                ('plc_DI', models.IntegerField(blank=True, null=True, verbose_name='Количество цифровых входов')),
                ('plc_DO', models.IntegerField(blank=True, null=True, verbose_name='Количество цифровых выходов')),
                ('plc_AI', models.IntegerField(blank=True, null=True, verbose_name='Количество аналоговых входов')),
                ('plc_AO', models.IntegerField(blank=True, null=True, verbose_name='Количество аналоговых выходов')),
                ('plc_UI', models.IntegerField(blank=True, null=True, verbose_name='Количество универсальных входов')),
                ('plc_UO', models.IntegerField(blank=True, null=True, verbose_name='Количество универсальных выходов')),
                ('plc_UIO', models.IntegerField(blank=True, null=True, verbose_name='Количество универсальных входов/выходов')),
                ('plc_io_qty', models.IntegerField(blank=True, null=True, verbose_name='Количество входов/выходов')),
                ('accessory', models.BooleanField(blank=True, default=False, null=True, verbose_name='Акссесуар или нет')),
                ('power_type', models.IntegerField(blank=True, choices=[(2, 'DC'), (1, 'AC')], null=True, verbose_name='Тип питающего напряжения')),
                ('voltage', models.FloatField(blank=True, null=True, verbose_name='Напряжение')),
                ('power', models.FloatField(blank=True, null=True, verbose_name='Мощность')),
                ('current', models.FloatField(blank=True, null=True, verbose_name='Ток')),
                ('work_temp_low', models.FloatField(blank=True, null=True, verbose_name='Рабочая температура нижняя')),
                ('work_temp_high', models.FloatField(blank=True, null=True, verbose_name='Рабочая температура верхняя')),
                ('port_qty', models.IntegerField(blank=True, null=True, verbose_name='Количество портов')),
                ('in_stock', models.FloatField(blank=True, db_index=True, null=True, verbose_name='Количество на складе')),
                ('in_box', models.BooleanField(blank=True, default=False, null=True, verbose_name='Монтаж в шкаф или нет')),
                ('accessories', models.ManyToManyField(blank=True, related_name='_good_accessories_+', to='catalog.good', verbose_name='Аксессуары')),
                ('cable_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.cables', verbose_name='Тип кабеля')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='interface',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('name', models.CharField(db_index=True, max_length=100, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('interface_type', models.CharField(blank=True, max_length=100, null=True, verbose_name='Тип интерфейса')),
                ('cable_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.cables', verbose_name='Тип кабеля')),
            ],
            options={
                'verbose_name': 'Сетевые интерфейс',
                'verbose_name_plural': 'Сетевые интерфейсы',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='subcategory1',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'Подкатегория 1',
                'verbose_name_plural': 'Подкатегории 1',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='subcategory2',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('subcategory1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.subcategory1', verbose_name='Подкатегория 1')),
            ],
            options={
                'verbose_name': 'Подкатегория 2',
                'verbose_name_plural': 'Подкатегории 2',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='unit',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('name', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='Наименование')),
                ('level', models.CharField(db_index=True, max_length=100, verbose_name='Единицы измерения')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='subfamily',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('family', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.family', verbose_name='Семейство')),
            ],
            options={
                'verbose_name': 'Подсемейство',
                'verbose_name_plural': 'Подсемейства',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='subcategory3',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер')),
                ('name', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='Наименование')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('subcategory2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.subcategory2', verbose_name='Подкатегория 2')),
            ],
            options={
                'verbose_name': 'Подкатегория 3',
                'verbose_name_plural': 'Подкатегории 3',
                'ordering': ['-name'],
            },
        ),
        migrations.CreateModel(
            name='kit_interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='количество')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.good')),
                ('interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.interface')),
            ],
        ),
        migrations.CreateModel(
            name='kit_control_interface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(blank=True, null=True, verbose_name='количество')),
                ('control_interface', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.control_interface')),
                ('good', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.good')),
            ],
        ),
        migrations.AddField(
            model_name='good',
            name='control_interfaces',
            field=models.ManyToManyField(through='catalog.kit_control_interface', to='catalog.control_interface', verbose_name='Управляющие интерфейсы'),
        ),
        migrations.AddField(
            model_name='good',
            name='good_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='good',
            name='good_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.family', verbose_name='Семейство'),
        ),
        migrations.AddField(
            model_name='good',
            name='network_interfaces',
            field=models.ManyToManyField(through='catalog.kit_interface', to='catalog.interface', verbose_name='Сетевые интерфейсы'),
        ),
        migrations.AddField(
            model_name='good',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.company', verbose_name='Производитель'),
        ),
        migrations.AddField(
            model_name='good',
            name='subcategory1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.subcategory1', verbose_name='Подкатегория 1'),
        ),
        migrations.AddField(
            model_name='good',
            name='subcategory2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.subcategory2', verbose_name='Подкатегория 2'),
        ),
        migrations.AddField(
            model_name='good',
            name='subcategory3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.subcategory3', verbose_name='Подкатегория 3'),
        ),
        migrations.AddField(
            model_name='good',
            name='subfamily',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.subfamily', verbose_name='Подсемейство'),
        ),
        migrations.AddField(
            model_name='good',
            name='suplayer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.company', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='good',
            name='twin',
            field=models.ManyToManyField(blank=True, related_name='_good_twin_+', to='catalog.good', verbose_name='Обязательный акссесуар'),
        ),
        migrations.AddField(
            model_name='good',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.unit', verbose_name='Единица измерения'),
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.contact', verbose_name='Контакт'),
        ),
        migrations.AddField(
            model_name='company',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.country', verbose_name='Страна происхождения'),
        ),
        migrations.AddField(
            model_name='company',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.country', verbose_name='Страна производства'),
        ),
        migrations.AddField(
            model_name='company',
            name='type',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.SET_DEFAULT, to='catalog.comp_type', verbose_name='Тип компании'),
        ),
    ]
