# Generated by Django 3.0.1 on 2020-01-15 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kit_control_interface',
            options={'verbose_name': 'Подключение', 'verbose_name_plural': 'Подключения'},
        ),
        migrations.AlterModelOptions(
            name='kit_interface',
            options={'verbose_name': 'Подключение', 'verbose_name_plural': 'Подключения'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='good',
            name='power_type',
            field=models.IntegerField(blank=True, choices=[(1, 'AC'), (2, 'DC')], null=True, verbose_name='Тип питающего напряжения'),
        ),
        migrations.AlterField(
            model_name='kit_control_interface',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='kit_interface',
            name='count',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='kit_interface',
            name='good',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.good', verbose_name='Номенклатура'),
        ),
        migrations.AlterField(
            model_name='kit_interface',
            name='interface',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.interface', verbose_name='Сетевой интерфейс'),
        ),
        migrations.AlterField(
            model_name='subcategory1',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CAT', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='subcategory1',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='subcategory2',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='subcategory2',
            name='subcategory1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SC1', to='catalog.subcategory1', verbose_name='Подкатегория 1'),
        ),
        migrations.AlterField(
            model_name='subcategory3',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='subcategory3',
            name='subcategory2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sc2', to='catalog.subcategory2', verbose_name='Подкатегория 2'),
        ),
    ]
