# Generated by Django 3.0.1 on 2020-01-15 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200115_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='power_type',
            field=models.IntegerField(blank=True, choices=[(2, 'DC'), (1, 'AC')], null=True, verbose_name='Тип питающего напряжения'),
        ),
    ]
