# Generated by Django 3.0.1 on 2020-01-15 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200115_2009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory1',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='subcategory1',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='subcategory2',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='subcategory2',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер'),
        ),
        migrations.AlterField(
            model_name='subcategory3',
            name='name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Наименование'),
        ),
        migrations.AlterField(
            model_name='subcategory3',
            name='no',
            field=models.AutoField(primary_key=True, serialize=False, unique=True, verbose_name='Номер'),
        ),
    ]
