# Generated by Django 3.0.1 on 2020-02-04 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20200115_2011'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='delivery_time',
        ),
        migrations.AlterField(
            model_name='good',
            name='good_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='CATEGORY', to='catalog.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='good',
            name='in_stock',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='Количество на складе'),
        ),
        migrations.AlterField(
            model_name='good',
            name='power_type',
            field=models.IntegerField(blank=True, choices=[(2, 'DC'), (1, 'AC')], null=True, verbose_name='Тип питающего напряжения'),
        ),
        migrations.AlterField(
            model_name='good',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='PRODUCER', to='catalog.company', verbose_name='Производитель'),
        ),
        migrations.AlterField(
            model_name='good',
            name='subcategory1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SUBCATEGORY1', to='catalog.subcategory1', verbose_name='Подкатегория 1'),
        ),
        migrations.AlterField(
            model_name='good',
            name='subcategory2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SUBCATEGORY2', to='catalog.subcategory2', verbose_name='Подкатегория 2'),
        ),
        migrations.AlterField(
            model_name='good',
            name='subcategory3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SUBCATEGORY3', to='catalog.subcategory3', verbose_name='Подкатегория 3'),
        ),
        migrations.AlterField(
            model_name='subcategory3',
            name='subcategory2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='SC2', to='catalog.subcategory2', verbose_name='Подкатегория 2'),
        ),
    ]
