# Generated by Django 3.0.1 on 2020-02-04 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200204_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='delivery_time',
            field=models.IntegerField(blank=True, null=True, verbose_name='Срок поставки'),
        ),
    ]
