# Generated by Django 3.0.1 on 2020-02-09 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_good_delivery_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='good',
            name='power_type',
            field=models.IntegerField(blank=True, choices=[(3, 'AC/DC'), (2, 'DC'), (1, 'AC')], null=True, verbose_name='Тип питающего напряжения'),
        ),
    ]
