# Generated by Django 3.0.1 on 2020-02-09 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200209_1253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='good',
            name='comission_time',
        ),
        migrations.RemoveField(
            model_name='good',
            name='discount_max',
        ),
        migrations.RemoveField(
            model_name='good',
            name='discount_standart',
        ),
        migrations.RemoveField(
            model_name='good',
            name='installation_time',
        ),
        migrations.RemoveField(
            model_name='good',
            name='multiplayer_min',
        ),
        migrations.RemoveField(
            model_name='good',
            name='multiplayer_standart',
        ),
        migrations.RemoveField(
            model_name='good',
            name='profit_min',
        ),
        migrations.RemoveField(
            model_name='good',
            name='profit_rrp',
        ),
        migrations.RemoveField(
            model_name='good',
            name='profit_standart',
        ),
        migrations.RemoveField(
            model_name='good',
            name='programming_time',
        ),
        migrations.RemoveField(
            model_name='good',
            name='purchase_price_w_vat',
        ),
        migrations.RemoveField(
            model_name='good',
            name='purchase_price_wo_vat',
        ),
        migrations.RemoveField(
            model_name='good',
            name='rrp_price_w_vat',
        ),
        migrations.RemoveField(
            model_name='good',
            name='rrp_wo_vat',
        ),
        migrations.AlterField(
            model_name='good',
            name='power_type',
            field=models.IntegerField(blank=True, choices=[(3, 'AC/DC'), (1, 'AC'), (2, 'DC')], null=True, verbose_name='Тип питающего напряжения'),
        ),
    ]
