# Generated by Django 3.0.1 on 2020-02-09 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_auto_20200209_1258'),
    ]

    operations = [
        migrations.AddField(
            model_name='good',
            name='comission_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Время на пуско - наладку'),
        ),
        migrations.AddField(
            model_name='good',
            name='discount_max',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Скидка максимальная'),
        ),
        migrations.AddField(
            model_name='good',
            name='discount_standart',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Скидка стандартная'),
        ),
        migrations.AddField(
            model_name='good',
            name='installation_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Время на монтаж'),
        ),
        migrations.AddField(
            model_name='good',
            name='multiplayer_min',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Наценка минимальная'),
        ),
        migrations.AddField(
            model_name='good',
            name='multiplayer_standart',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Наценка стандартная'),
        ),
        migrations.AddField(
            model_name='good',
            name='profit_min',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=50, null=True, verbose_name='Прибыль при максимальной скидке'),
        ),
        migrations.AddField(
            model_name='good',
            name='profit_rrp',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=50, null=True, verbose_name='Прибыль от розницы'),
        ),
        migrations.AddField(
            model_name='good',
            name='profit_standart',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=50, null=True, verbose_name='Прибыль при стандартной скидке'),
        ),
        migrations.AddField(
            model_name='good',
            name='programming_time',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=50, null=True, verbose_name='Время на программирование'),
        ),
        migrations.AddField(
            model_name='good',
            name='purchase_price_w_vat',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=50, null=True, verbose_name='Закупочная цена, с НДС'),
        ),
        migrations.AddField(
            model_name='good',
            name='purchase_price_wo_vat',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=50, null=True, verbose_name='Закупочная цена, без НДС'),
        ),
        migrations.AddField(
            model_name='good',
            name='rrp_price_w_vat',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=50, null=True, verbose_name='Розница, с НДС'),
        ),
        migrations.AddField(
            model_name='good',
            name='rrp_wo_vat',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=2, max_digits=50, null=True, verbose_name='Розница, без НДС'),
        ),
        migrations.AlterField(
            model_name='good',
            name='power_type',
            field=models.IntegerField(blank=True, choices=[(1, 'AC'), (2, 'DC'), (3, 'AC/DC')], null=True, verbose_name='Тип питающего напряжения'),
        ),
    ]
